"""initial migration

Revision ID: 8c17228d37f5
Revises: 
Create Date: 2024-08-10 10:31:21.333926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c17228d37f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habit_tracking_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_habit_tracking_types'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.CheckConstraint("username NOT LIKE '%[^a-zA-Z0-9_]%'", name=op.f('ck_users_username_no_special_chars')),
    sa.CheckConstraint('length(username)>5 AND length(username)>30', name=op.f('ck_users_username_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('habit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('habit_tracking_type_id', sa.UUID(), nullable=False),
    sa.Column('recurrence_pattern', sa.String(), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['habit_tracking_type_id'], ['habit_tracking_types.id'], name=op.f('fk_habit_habit_tracking_type_id_habit_tracking_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_habit'))
    )
    op.create_table('habit_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('habit_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habit.id'], name=op.f('fk_habit_values_habit_id_habit')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_habit_values'))
    )
    op.create_table('user_habits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('habit_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habit.id'], name=op.f('fk_user_habits_habit_id_habit')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_habits_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_habits'))
    )
    op.create_table('habit_occurances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('habit_id', sa.UUID(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('dt_completed', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('habit_value_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habit.id'], name=op.f('fk_habit_occurances_habit_id_habit')),
    sa.ForeignKeyConstraint(['habit_value_id'], ['habit_values.id'], name=op.f('fk_habit_occurances_habit_value_id_habit_values')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_habit_occurances'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habit_occurances')
    op.drop_table('user_habits')
    op.drop_table('habit_values')
    op.drop_table('habit')
    op.drop_table('users')
    op.drop_table('habit_tracking_types')
    # ### end Alembic commands ###
